apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo-app-deployment
spec:
  selector:
    matchLabels:
      app: flask-demo-app
  template:
    metadata:
      labels:
        app: flask-demo-app
    spec:
      volumes:
        - name: name-me
          hostPath:
            path: /home/docker/
      containers:
        - image: 2kunal6/test-images:latest
          name: test-image-name
          volumeMounts:
            - name: name-me
              mountPath: /app/in_container_location/
